# Generated by Django 2.1.7 on 2019-03-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
